apiVersion: v1
kind: Service
metadata:
  labels:
    app: dataspace-connector
  name: dataspace-connector
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: dataspace-connector
