name: docker_image

on:
   push:
    branches: [ master, develop ]
    tags: 'v*'
   release:
     types: [published]
   schedule:
      - cron: '0 4 * * *'
      
env:
  REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  OWNER: ${{ secrets.REPO_USER }}
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: Build docker image
        run: |
          TAG=$REGISTRY/$OWNER/dataspaceconnector/dataspace-connector:dev
          readonly TAG
          docker build . -t $TAG
      -
       name: Login to registry
       uses: docker/login-action@v1
       with:
         # This should use REGISTRY instead of the secret directly
         registry: ${{ secrets.IMAGE_REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      -
       name: Push image
       run: |
        # This will have to be moved/joined with the TAG from above
        TAG=$REGISTRY/$OWNER/dataspaceconnector/dataspace-connector:dev
        docker push $TAG
