name: docker_image

on:
   push:
    branches: [ master, develop ]
    tags: 'v*'
   release:
     types: [published]
   #schedule:
   #   - cron: '0 4 * * *'
      
env:
  REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  OWNER: ${{ secrets.REPO_USER }}
    
jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: Build registry path
        id: get_repo
        run: echo ::set-output name=IMAGE::"$REGISTRY/$OWNER/dataspaceconnector/dataspace-connector"
      -
       name: Find tag
       id: get_tag
       run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      -
       name: Find branch name
       id: get_branch
       run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      -
       name: Login to registry
       uses: docker/login-action@v1
       with:
         # This should use REGISTRY instead of the secret directly
         registry: ${{ secrets.IMAGE_REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      -
       name: Build image
       run: |
        docker build . -t ${{ steps.get_repo.outputs.IMAGE }}:${{ steps.get_branch.outputs.BRANCH }}
      -
       name: Push image
       run: |
         echo "Image: ${{ steps.get_repo.outputs.IMAGE }}"
         echo "Branch: ${{ steps.get_branch.outputs.BRANCH }}"
         echo "Tag: ${{ steps.get_tag.outputs.TAG }}"
         TAG=${{ steps.get_tag.outputs.TAG }}
         if [[ $TAG == v* ]]
         then
           # Its a version tag
           TAG=${TAG:1:${#TAG}}
           echo "Found a version tag"
           if [[ ${{ steps.get_branch.outputs.BRANCH }} == 'master' ]]
           then
             # Its a release version tag
             docker tag ${{ steps.get_repo.outputs.IMAGE }}:${{ steps.get_branch.outputs.BRANCH }} ${{ steps.get_repo.outputs.IMAGE }}:latest
             docker push ${{ steps.get_repo.outputs.IMAGE }}:latest
          fi
         fi
         if [[ ${#TAG} != 0]]
           # Has tag
           docker tag ${{ steps.get_repo.outputs.IMAGE }}:${{ steps.get_branch.outputs.BRANCH }} ${{ steps.get_repo.outputs.IMAGE }}:{$TAG}
           docker push ${{ steps.get_repo.outputs.IMAGE }}:{$TAG}
         fi
         docker push ${{ get_repo.outputs.IMAGE }}:${{ steps.get_branch.outputs.BRANCH }}
